plugins:
  migratepassword_enabled:
    default: true
    client: false
  migratepassword_allow_insecure_passwords:
    default: false
    client: false
  min_first_post_length:
    client: true
    min: 0
    default: 0
